<?php

declare(strict_types=1);

return [

    'currency' => env('BRICK_MONEY_CURRENCY', 'USD'),

    'major' => env('BRICK_MONEY_MAJOR', false),

    'currencies' => [

        'AED' => [
            'name' => 'UAE Dirham',
            'numeric_code' => 784,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => 'د.إ',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'AFN' => [
            'name' => 'Afghani',
            'numeric_code' => 971,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => '؋',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'ALL' => [
            'name' => 'Lek',
            'numeric_code' => 8,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => 'L',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'AMD' => [
            'name' => 'Armenian Dram',
            'numeric_code' => 51,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => 'դր.',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'ANG' => [
            'name' => 'Netherlands Antillean Guilder',
            'numeric_code' => 532,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => 'ƒ',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => ',',
            'thousand_separator' => '.',
        ],

        'AOA' => [
            'name' => 'Kwanza',
            'numeric_code' => 973,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => 'Kz',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'ARS' => [
            'name' => 'Argentine Peso',
            'numeric_code' => 32,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => '$',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => ',',
            'thousand_separator' => '.',
        ],

        'AUD' => [
            'name' => 'Australian Dollar',
            'numeric_code' => 36,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => '$',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ' ',
        ],

        'AWG' => [
            'name' => 'Aruban Florin',
            'numeric_code' => 533,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => 'ƒ',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'AZN' => [
            'name' => 'Azerbaijanian Manat',
            'numeric_code' => 944,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => '₼',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'BAM' => [
            'name' => 'Convertible Mark',
            'numeric_code' => 977,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => 'КМ',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'BBD' => [
            'name' => 'Barbados Dollar',
            'numeric_code' => 52,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => '$',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'BDT' => [
            'name' => 'Taka',
            'numeric_code' => 50,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => '৳',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'BGN' => [
            'name' => 'Bulgarian Lev',
            'numeric_code' => 975,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => 'лв',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => ',',
            'thousand_separator' => ' ',
        ],

        'BHD' => [
            'name' => 'Bahraini Dinar',
            'numeric_code' => 48,
            'decimal_places' => 3,
            'subunit' => 1000,
            'symbol' => 'ب.د',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'BIF' => [
            'name' => 'Burundi Franc',
            'numeric_code' => 108,
            'decimal_places' => 0,
            'subunit' => 1,
            'symbol' => 'Fr',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'BMD' => [
            'name' => 'Bermudian Dollar',
            'numeric_code' => 60,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => '$',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'BND' => [
            'name' => 'Brunei Dollar',
            'numeric_code' => 96,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => '$',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'BOB' => [
            'name' => 'Boliviano',
            'numeric_code' => 68,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => 'Bs.',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'BOV' => [
            'name' => 'Mvdol',
            'numeric_code' => 984,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => 'Bs.',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'BRL' => [
            'name' => 'Brazilian Real',
            'numeric_code' => 986,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => 'R$',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => ',',
            'thousand_separator' => '.',
        ],

        'BSD' => [
            'name' => 'Bahamian Dollar',
            'numeric_code' => 44,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => '$',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'BTN' => [
            'name' => 'Ngultrum',
            'numeric_code' => 64,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => 'Nu.',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'BWP' => [
            'name' => 'Pula',
            'numeric_code' => 72,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => 'P',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'BYN' => [
            'name' => 'Belarussian Ruble',
            'numeric_code' => 974,
            'decimal_places' => 0,
            'subunit' => 1,
            'symbol' => 'Br',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => ',',
            'thousand_separator' => ' ',
        ],

        'BZD' => [
            'name' => 'Belize Dollar',
            'numeric_code' => 84,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => '$',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'CAD' => [
            'name' => 'Canadian Dollar',
            'numeric_code' => 124,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => '$',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'CDF' => [
            'name' => 'Congolese Franc',
            'numeric_code' => 976,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => 'Fr',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'CHF' => [
            'name' => 'Swiss Franc',
            'numeric_code' => 756,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => 'CHF',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'CLF' => [
            'name' => 'Unidades de fomento',
            'numeric_code' => 990,
            'decimal_places' => 0,
            'subunit' => 1,
            'symbol' => 'UF',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => ',',
            'thousand_separator' => '.',
        ],

        'CLP' => [
            'name' => 'Chilean Peso',
            'numeric_code' => 152,
            'decimal_places' => 0,
            'subunit' => 1,
            'symbol' => '$',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => ',',
            'thousand_separator' => '.',
        ],

        'CNY' => [
            'name' => 'Yuan Renminbi',
            'numeric_code' => 156,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => '¥',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'COP' => [
            'name' => 'Colombian Peso',
            'numeric_code' => 170,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => '$',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => ',',
            'thousand_separator' => '.',
        ],

        'CRC' => [
            'name' => 'Costa Rican Colon',
            'numeric_code' => 188,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => '₡',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => ',',
            'thousand_separator' => '.',
        ],

        'CUC' => [
            'name' => 'Peso Convertible',
            'numeric_code' => 931,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => '$',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'CUP' => [
            'name' => 'Cuban Peso',
            'numeric_code' => 192,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => '$',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'CVE' => [
            'name' => 'Cape Verde Escudo',
            'numeric_code' => 132,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => '$',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'CZK' => [
            'name' => 'Czech Koruna',
            'numeric_code' => 203,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => 'Kč',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => ',',
            'thousand_separator' => '.',
        ],

        'DJF' => [
            'name' => 'Djibouti Franc',
            'numeric_code' => 262,
            'decimal_places' => 0,
            'subunit' => 1,
            'symbol' => 'Fdj',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'DKK' => [
            'name' => 'Danish Krone',
            'numeric_code' => 208,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => 'kr',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => ',',
            'thousand_separator' => '.',
        ],

        'DOP' => [
            'name' => 'Dominican Peso',
            'numeric_code' => 214,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => '$',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'DZD' => [
            'name' => 'Algerian Dinar',
            'numeric_code' => 12,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => 'د.ج',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'EGP' => [
            'name' => 'Egyptian Pound',
            'numeric_code' => 818,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => 'ج.م',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'ERN' => [
            'name' => 'Nakfa',
            'numeric_code' => 232,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => 'Nfk',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'ETB' => [
            'name' => 'Ethiopian Birr',
            'numeric_code' => 230,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => 'Br',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'EUR' => [
            'name' => 'Euro',
            'numeric_code' => 978,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => '€',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => ',',
            'thousand_separator' => '.',
        ],

        'FJD' => [
            'name' => 'Fiji Dollar',
            'numeric_code' => 242,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => '$',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'FKP' => [
            'name' => 'Falkland Islands Pound',
            'numeric_code' => 238,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => '£',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'GBP' => [
            'name' => 'Pound Sterling',
            'numeric_code' => 826,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => '£',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'GEL' => [
            'name' => 'Lari',
            'numeric_code' => 981,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => '₾',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'GHS' => [
            'name' => 'Ghana Cedi',
            'numeric_code' => 936,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => '₵',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'GIP' => [
            'name' => 'Gibraltar Pound',
            'numeric_code' => 292,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => '£',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'GMD' => [
            'name' => 'Dalasi',
            'numeric_code' => 270,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => 'D',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'GNF' => [
            'name' => 'Guinea Franc',
            'numeric_code' => 324,
            'decimal_places' => 0,
            'subunit' => 1,
            'symbol' => 'Fr',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'GTQ' => [
            'name' => 'Quetzal',
            'numeric_code' => 320,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => 'Q',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'GYD' => [
            'name' => 'Guyana Dollar',
            'numeric_code' => 328,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => '$',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'HKD' => [
            'name' => 'Hong Kong Dollar',
            'numeric_code' => 344,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => '$',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'HNL' => [
            'name' => 'Lempira',
            'numeric_code' => 340,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => 'L',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'HRK' => [
            'name' => 'Croatian Kuna',
            'numeric_code' => 191,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => 'kn',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => ',',
            'thousand_separator' => '.',
        ],

        'HTG' => [
            'name' => 'Gourde',
            'numeric_code' => 332,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => 'G',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'HUF' => [
            'name' => 'Forint',
            'numeric_code' => 348,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => 'Ft',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => ',',
            'thousand_separator' => '.',
        ],

        'IDR' => [
            'name' => 'Rupiah',
            'numeric_code' => 360,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => 'Rp',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => ',',
            'thousand_separator' => '.',
        ],

        'ILS' => [
            'name' => 'New Israeli Sheqel',
            'numeric_code' => 376,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => '₪',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'INR' => [
            'name' => 'Indian Rupee',
            'numeric_code' => 356,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => '₹',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'IQD' => [
            'name' => 'Iraqi Dinar',
            'numeric_code' => 368,
            'decimal_places' => 3,
            'subunit' => 1000,
            'symbol' => 'ع.د',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'IRR' => [
            'name' => 'Iranian Rial',
            'numeric_code' => 364,
            'decimal_places' => 0,
            'subunit' => 1,
            'symbol' => '﷼',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'ISK' => [
            'name' => 'Iceland Krona',
            'numeric_code' => 352,
            'decimal_places' => 0,
            'subunit' => 1,
            'symbol' => 'kr',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => ',',
            'thousand_separator' => '.',
        ],

        'JMD' => [
            'name' => 'Jamaican Dollar',
            'numeric_code' => 388,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => '$',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'JOD' => [
            'name' => 'Jordanian Dinar',
            'numeric_code' => 400,
            'decimal_places' => 3,
            'subunit' => 100,
            'symbol' => 'د.ا',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'JPY' => [
            'name' => 'Yen',
            'numeric_code' => 392,
            'decimal_places' => 0,
            'subunit' => 1,
            'symbol' => '¥',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'KES' => [
            'name' => 'Kenyan Shilling',
            'numeric_code' => 404,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => 'KSh',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'KGS' => [
            'name' => 'Som',
            'numeric_code' => 417,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => 'som',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'KHR' => [
            'name' => 'Riel',
            'numeric_code' => 116,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => '៛',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'KMF' => [
            'name' => 'Comoro Franc',
            'numeric_code' => 174,
            'decimal_places' => 0,
            'subunit' => 1,
            'symbol' => 'Fr',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'KPW' => [
            'name' => 'North Korean Won',
            'numeric_code' => 408,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => '₩',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'KRW' => [
            'name' => 'Won',
            'numeric_code' => 410,
            'decimal_places' => 0,
            'subunit' => 1,
            'symbol' => '₩',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'KWD' => [
            'name' => 'Kuwaiti Dinar',
            'numeric_code' => 414,
            'decimal_places' => 3,
            'subunit' => 1000,
            'symbol' => 'د.ك',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'KYD' => [
            'name' => 'Cayman Islands Dollar',
            'numeric_code' => 136,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => '$',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'KZT' => [
            'name' => 'Tenge',
            'numeric_code' => 398,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => '〒',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'LAK' => [
            'name' => 'Kip',
            'numeric_code' => 418,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => '₭',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'LBP' => [
            'name' => 'Lebanese Pound',
            'numeric_code' => 422,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => 'ل.ل',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'LKR' => [
            'name' => 'Sri Lanka Rupee',
            'numeric_code' => 144,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => '₨',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'LRD' => [
            'name' => 'Liberian Dollar',
            'numeric_code' => 430,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => '$',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'LSL' => [
            'name' => 'Loti',
            'numeric_code' => 426,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => 'L',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'LTL' => [
            'name' => 'Lithuanian Litas',
            'numeric_code' => 440,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => 'Lt',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'LVL' => [
            'name' => 'Latvian Lats',
            'numeric_code' => 428,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => 'Ls',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'LYD' => [
            'name' => 'Libyan Dinar',
            'numeric_code' => 434,
            'decimal_places' => 3,
            'subunit' => 1000,
            'symbol' => 'ل.د',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'MAD' => [
            'name' => 'Moroccan Dirham',
            'numeric_code' => 504,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => 'د.م.',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'MDL' => [
            'name' => 'Moldovan Leu',
            'numeric_code' => 498,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => 'L',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'MGA' => [
            'name' => 'Malagasy Ariary',
            'numeric_code' => 969,
            'decimal_places' => 2,
            'subunit' => 5,
            'symbol' => 'Ar',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'MKD' => [
            'name' => 'Denar',
            'numeric_code' => 807,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => 'ден',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'MMK' => [
            'name' => 'Kyat',
            'numeric_code' => 104,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => 'K',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'MNT' => [
            'name' => 'Tugrik',
            'numeric_code' => 496,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => '₮',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'MOP' => [
            'name' => 'Pataca',
            'numeric_code' => 446,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => 'P',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'MRO' => [
            'name' => 'Ouguiya',
            'numeric_code' => 478,
            'decimal_places' => 2,
            'subunit' => 5,
            'symbol' => 'UM',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'MUR' => [
            'name' => 'Mauritius Rupee',
            'numeric_code' => 480,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => '₨',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'MVR' => [
            'name' => 'Rufiyaa',
            'numeric_code' => 462,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => 'MVR',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'MWK' => [
            'name' => 'Kwacha',
            'numeric_code' => 454,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => 'MK',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'MXN' => [
            'name' => 'Mexican Peso',
            'numeric_code' => 484,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => '$',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'MYR' => [
            'name' => 'Malaysian Ringgit',
            'numeric_code' => 458,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => 'RM',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'MZN' => [
            'name' => 'Mozambique Metical',
            'numeric_code' => 943,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => 'MTn',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => ',',
            'thousand_separator' => '.',
        ],

        'NAD' => [
            'name' => 'Namibia Dollar',
            'numeric_code' => 516,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => '$',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'NGN' => [
            'name' => 'Naira',
            'numeric_code' => 566,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => '₦',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'NIO' => [
            'name' => 'Cordoba Oro',
            'numeric_code' => 558,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => 'C$',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'NOK' => [
            'name' => 'Norwegian Krone',
            'numeric_code' => 578,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => 'kr',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => ',',
            'thousand_separator' => '.',
        ],

        'NPR' => [
            'name' => 'Nepalese Rupee',
            'numeric_code' => 524,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => '₨',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'NZD' => [
            'name' => 'New Zealand Dollar',
            'numeric_code' => 554,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => '$',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'OMR' => [
            'name' => 'Rial Omani',
            'numeric_code' => 512,
            'decimal_places' => 3,
            'subunit' => 1000,
            'symbol' => 'ر.ع.',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'PAB' => [
            'name' => 'Balboa',
            'numeric_code' => 590,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => 'B/.',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'PEN' => [
            'name' => 'Sol',
            'numeric_code' => 604,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => 'S/',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'PGK' => [
            'name' => 'Kina',
            'numeric_code' => 598,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => 'K',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'PHP' => [
            'name' => 'Philippine Peso',
            'numeric_code' => 608,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => '₱',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'PKR' => [
            'name' => 'Pakistan Rupee',
            'numeric_code' => 586,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => '₨',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'PLN' => [
            'name' => 'Zloty',
            'numeric_code' => 985,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => 'zł',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => ',',
            'thousand_separator' => ' ',
        ],

        'PYG' => [
            'name' => 'Guarani',
            'numeric_code' => 600,
            'decimal_places' => 0,
            'subunit' => 1,
            'symbol' => '₲',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'QAR' => [
            'name' => 'Qatari Rial',
            'numeric_code' => 634,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => 'ر.ق',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'RON' => [
            'name' => 'New Romanian Leu',
            'numeric_code' => 946,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => 'Lei',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => ',',
            'thousand_separator' => '.',
        ],

        'RSD' => [
            'name' => 'Serbian Dinar',
            'numeric_code' => 941,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => 'РСД',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'RUB' => [
            'name' => 'Russian Ruble',
            'numeric_code' => 643,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => '₽',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => ',',
            'thousand_separator' => '.',
        ],

        'RWF' => [
            'name' => 'Rwanda Franc',
            'numeric_code' => 646,
            'decimal_places' => 0,
            'subunit' => 1,
            'symbol' => 'FRw',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'SAR' => [
            'name' => 'Saudi Riyal',
            'numeric_code' => 682,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => 'ر.س',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'SBD' => [
            'name' => 'Solomon Islands Dollar',
            'numeric_code' => 90,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => '$',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'SCR' => [
            'name' => 'Seychelles Rupee',
            'numeric_code' => 690,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => '₨',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'SDG' => [
            'name' => 'Sudanese Pound',
            'numeric_code' => 938,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => '£',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'SEK' => [
            'name' => 'Swedish Krona',
            'numeric_code' => 752,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => 'kr',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => ',',
            'thousand_separator' => ' ',
        ],

        'SGD' => [
            'name' => 'Singapore Dollar',
            'numeric_code' => 702,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => '$',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'SHP' => [
            'name' => 'Saint Helena Pound',
            'numeric_code' => 654,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => '£',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'SLL' => [
            'name' => 'Leone',
            'numeric_code' => 694,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => 'Le',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'SOS' => [
            'name' => 'Somali Shilling',
            'numeric_code' => 706,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => 'Sh',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'SRD' => [
            'name' => 'Surinam Dollar',
            'numeric_code' => 968,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => '$',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'SSP' => [
            'name' => 'South Sudanese Pound',
            'numeric_code' => 728,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => '£',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'STD' => [
            'name' => 'Dobra',
            'numeric_code' => 678,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => 'Db',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'SVC' => [
            'name' => 'El Salvador Colon',
            'numeric_code' => 222,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => '₡',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'SYP' => [
            'name' => 'Syrian Pound',
            'numeric_code' => 760,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => '£S',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'SZL' => [
            'name' => 'Lilangeni',
            'numeric_code' => 748,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => 'E',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'THB' => [
            'name' => 'Baht',
            'numeric_code' => 764,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => '฿',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'TJS' => [
            'name' => 'Somoni',
            'numeric_code' => 972,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => 'ЅМ',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'TMT' => [
            'name' => 'Turkmenistan New Manat',
            'numeric_code' => 934,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => 'T',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'TND' => [
            'name' => 'Tunisian Dinar',
            'numeric_code' => 788,
            'decimal_places' => 3,
            'subunit' => 1000,
            'symbol' => 'د.ت',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'TOP' => [
            'name' => 'Pa’anga',
            'numeric_code' => 776,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => 'T$',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'TRY' => [
            'name' => 'Turkish Lira',
            'numeric_code' => 949,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => '₺',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => ',',
            'thousand_separator' => '.',
        ],

        'TTD' => [
            'name' => 'Trinidad and Tobago Dollar',
            'numeric_code' => 780,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => '$',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'TWD' => [
            'name' => 'New Taiwan Dollar',
            'numeric_code' => 901,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => '$',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'TZS' => [
            'name' => 'Tanzanian Shilling',
            'numeric_code' => 834,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => 'Sh',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'UAH' => [
            'name' => 'Hryvnia',
            'numeric_code' => 980,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => '₴',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'UGX' => [
            'name' => 'Uganda Shilling',
            'numeric_code' => 800,
            'decimal_places' => 0,
            'subunit' => 1,
            'symbol' => 'USh',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'USD' => [
            'name' => 'US Dollar',
            'numeric_code' => 840,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => '$',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'UYU' => [
            'name' => 'Peso Uruguayo',
            'numeric_code' => 858,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => '$',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => ',',
            'thousand_separator' => '.',
        ],

        'UZS' => [
            'name' => 'Uzbekistan Sum',
            'numeric_code' => 860,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => 'лв',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'VEF' => [
            'name' => 'Bolivar',
            'numeric_code' => 937,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => 'Bs F',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => ',',
            'thousand_separator' => '.',
        ],

        'VES' => [
            'name' => 'Bolívar Soberano',
            'numeric_code' => 928,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => 'Bs S',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => ',',
            'thousand_separator' => '.',
        ],

        'VED' => [
            'name' => 'Dijital Bolívar',
            'numeric_code' => 926,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => 'Bs D',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => ',',
            'thousand_separator' => '.',
        ],

        'VND' => [
            'name' => 'Dong',
            'numeric_code' => 704,
            'decimal_places' => 0,
            'subunit' => 1,
            'symbol' => '₫',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => ',',
            'thousand_separator' => '.',
        ],

        'VUV' => [
            'name' => 'Vatu',
            'numeric_code' => 548,
            'decimal_places' => 0,
            'subunit' => 1,
            'symbol' => 'Vt',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'WST' => [
            'name' => 'Tala',
            'numeric_code' => 882,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => 'T',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'XAF' => [
            'name' => 'CFA Franc BEAC',
            'numeric_code' => 950,
            'decimal_places' => 0,
            'subunit' => 1,
            'symbol' => 'Fr',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'XAG' => [
            'name' => 'Silver',
            'numeric_code' => 961,
            'decimal_places' => 0,
            'subunit' => 1,
            'symbol' => 'oz t',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'XAU' => [
            'name' => 'Gold',
            'numeric_code' => 959,
            'decimal_places' => 0,
            'subunit' => 1,
            'symbol' => 'oz t',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'XCD' => [
            'name' => 'East Caribbean Dollar',
            'numeric_code' => 951,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => '$',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'XDR' => [
            'name' => 'SDR (Special Drawing Right)',
            'numeric_code' => 960,
            'decimal_places' => 0,
            'subunit' => 1,
            'symbol' => 'SDR',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'XOF' => [
            'name' => 'CFA Franc BCEAO',
            'numeric_code' => 952,
            'decimal_places' => 0,
            'subunit' => 1,
            'symbol' => 'Fr',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'XPF' => [
            'name' => 'CFP Franc',
            'numeric_code' => 953,
            'decimal_places' => 0,
            'subunit' => 1,
            'symbol' => 'Fr',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'YER' => [
            'name' => 'Yemeni Rial',
            'numeric_code' => 886,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => '﷼',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'ZAR' => [
            'name' => 'Rand',
            'numeric_code' => 710,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => 'R',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'ZMW' => [
            'name' => 'Zambian Kwacha',
            'numeric_code' => 967,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => 'ZK',
            'symbol_first' => false,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

        'ZWL' => [
            'name' => 'Zimbabwe Dollar',
            'numeric_code' => 932,
            'decimal_places' => 2,
            'subunit' => 100,
            'symbol' => '$',
            'symbol_first' => true,
            'symbol_spaced' => false,
            'decimal_separator' => '.',
            'thousand_separator' => ',',
        ],

    ],

];
